// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  AddServiceData,
  AddServiceResponses,
  CreateAlertTargetData,
  CreateAlertTargetResponses,
  CreatePluginData,
  CreatePluginResponses,
  DeleteAlertTargetData,
  DeleteAlertTargetResponses,
  DeletePluginData,
  DeletePluginResponses,
  DeleteServiceData,
  DeleteServiceResponses,
  GetAlertTargetsData,
  GetAlertTargetsResponses,
  GetCatalogData,
  GetCatalogResponses,
  GetHistoryData,
  GetHistoryErrors,
  GetHistoryResponses,
  GetIncidentByIdData,
  GetIncidentByIdErrors,
  GetIncidentByIdResponses,
  GetIncidentsData,
  GetIncidentsResponses,
  GetPluginsData,
  GetPluginsResponses,
  GetPublicIncidentsData,
  GetPublicIncidentsResponses,
  GetPublicServicesData,
  GetPublicServicesResponses,
  GetPublicStatusData,
  GetPublicStatusResponses,
  GetServiceByIdData,
  GetServiceByIdErrors,
  GetServiceByIdResponses,
  GetServicesData,
  GetServicesResponses,
  GetStatusData,
  GetStatusResponses,
  TestAlertTargetData,
  TestAlertTargetResponses,
  UpdatePluginData,
  UpdatePluginResponses,
  UpdateServiceData,
  UpdateServiceResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Aggregate status overview
 */
export const getStatus = <ThrowOnError extends boolean = false>(
  options?: Options<GetStatusData, ThrowOnError>
) =>
  (options?.client ?? client).get<GetStatusResponses, unknown, ThrowOnError>({
    url: "/status",
    ...options,
  });

/**
 * List monitored services
 */
export const getServices = <ThrowOnError extends boolean = false>(
  options?: Options<GetServicesData, ThrowOnError>
) =>
  (options?.client ?? client).get<GetServicesResponses, unknown, ThrowOnError>({
    url: "/services",
    ...options,
  });

/**
 * Add/enable a vendor for monitoring
 */
export const addService = <ThrowOnError extends boolean = false>(
  options: Options<AddServiceData, ThrowOnError>
) =>
  (options.client ?? client).post<AddServiceResponses, unknown, ThrowOnError>({
    url: "/services",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List all available vendors from catalog
 */
export const getCatalog = <ThrowOnError extends boolean = false>(
  options?: Options<GetCatalogData, ThrowOnError>
) =>
  (options?.client ?? client).get<GetCatalogResponses, unknown, ThrowOnError>({
    url: "/services/catalog/all",
    ...options,
  });

/**
 * Delete a service
 */
export const deleteService = <ThrowOnError extends boolean = false>(
  options: Options<DeleteServiceData, ThrowOnError>
) =>
  (options.client ?? client).delete<DeleteServiceResponses, unknown, ThrowOnError>({
    url: "/services/{id}",
    ...options,
  });

/**
 * Get service details with components
 */
export const getServiceById = <ThrowOnError extends boolean = false>(
  options: Options<GetServiceByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<GetServiceByIdResponses, GetServiceByIdErrors, ThrowOnError>({
    url: "/services/{id}",
    ...options,
  });

/**
 * Update a service
 */
export const updateService = <ThrowOnError extends boolean = false>(
  options: Options<UpdateServiceData, ThrowOnError>
) =>
  (options.client ?? client).patch<UpdateServiceResponses, unknown, ThrowOnError>({
    url: "/services/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List incidents
 */
export const getIncidents = <ThrowOnError extends boolean = false>(
  options?: Options<GetIncidentsData, ThrowOnError>
) =>
  (options?.client ?? client).get<GetIncidentsResponses, unknown, ThrowOnError>({
    url: "/incidents",
    ...options,
  });

/**
 * Get incident with updates
 */
export const getIncidentById = <ThrowOnError extends boolean = false>(
  options: Options<GetIncidentByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<GetIncidentByIdResponses, GetIncidentByIdErrors, ThrowOnError>({
    url: "/incidents/{id}",
    ...options,
  });

/**
 * Public aggregate status overview (no auth)
 */
export const getPublicStatus = <ThrowOnError extends boolean = false>(
  options?: Options<GetPublicStatusData, ThrowOnError>
) =>
  (options?.client ?? client).get<GetPublicStatusResponses, unknown, ThrowOnError>({
    url: "/public/status",
    ...options,
  });

/**
 * Public list of enabled services (no auth)
 */
export const getPublicServices = <ThrowOnError extends boolean = false>(
  options?: Options<GetPublicServicesData, ThrowOnError>
) =>
  (options?.client ?? client).get<GetPublicServicesResponses, unknown, ThrowOnError>({
    url: "/public/services",
    ...options,
  });

/**
 * Public list of active incidents (no auth)
 */
export const getPublicIncidents = <ThrowOnError extends boolean = false>(
  options?: Options<GetPublicIncidentsData, ThrowOnError>
) =>
  (options?.client ?? client).get<GetPublicIncidentsResponses, unknown, ThrowOnError>({
    url: "/public/incidents",
    ...options,
  });

/**
 * List alert targets
 */
export const getAlertTargets = <ThrowOnError extends boolean = false>(
  options?: Options<GetAlertTargetsData, ThrowOnError>
) =>
  (options?.client ?? client).get<GetAlertTargetsResponses, unknown, ThrowOnError>({
    url: "/alert-targets",
    ...options,
  });

/**
 * Create an alert target
 */
export const createAlertTarget = <ThrowOnError extends boolean = false>(
  options: Options<CreateAlertTargetData, ThrowOnError>
) =>
  (options.client ?? client).post<CreateAlertTargetResponses, unknown, ThrowOnError>({
    url: "/alert-targets",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete an alert target
 */
export const deleteAlertTarget = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAlertTargetData, ThrowOnError>
) =>
  (options.client ?? client).delete<DeleteAlertTargetResponses, unknown, ThrowOnError>({
    url: "/alert-targets/{id}",
    ...options,
  });

/**
 * Send a test alert
 */
export const testAlertTarget = <ThrowOnError extends boolean = false>(
  options: Options<TestAlertTargetData, ThrowOnError>
) =>
  (options.client ?? client).post<TestAlertTargetResponses, unknown, ThrowOnError>({
    url: "/alert-targets/{id}/test",
    ...options,
  });

/**
 * List plugins
 */
export const getPlugins = <ThrowOnError extends boolean = false>(
  options?: Options<GetPluginsData, ThrowOnError>
) =>
  (options?.client ?? client).get<GetPluginsResponses, unknown, ThrowOnError>({
    url: "/plugins",
    ...options,
  });

/**
 * Register a custom status plugin
 */
export const createPlugin = <ThrowOnError extends boolean = false>(
  options: Options<CreatePluginData, ThrowOnError>
) =>
  (options.client ?? client).post<CreatePluginResponses, unknown, ThrowOnError>({
    url: "/plugins",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get uptime history and status changes for a service
 */
export const getHistory = <ThrowOnError extends boolean = false>(
  options: Options<GetHistoryData, ThrowOnError>
) =>
  (options.client ?? client).get<GetHistoryResponses, GetHistoryErrors, ThrowOnError>({
    url: "/history/{serviceId}",
    ...options,
  });

/**
 * Delete a plugin and its service
 */
export const deletePlugin = <ThrowOnError extends boolean = false>(
  options: Options<DeletePluginData, ThrowOnError>
) =>
  (options.client ?? client).delete<DeletePluginResponses, unknown, ThrowOnError>({
    url: "/plugins/{id}",
    ...options,
  });

/**
 * Update a plugin
 */
export const updatePlugin = <ThrowOnError extends boolean = false>(
  options: Options<UpdatePluginData, ThrowOnError>
) =>
  (options.client ?? client).patch<UpdatePluginResponses, unknown, ThrowOnError>({
    url: "/plugins/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
