// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}/api` | (string & {});
};

export type NormalizedStatus = "operational" | "degraded" | "outage" | "maintenance";

export type Service = {
  id: string;
  vendorId: string;
  name: string;
  category: string;
  status: string;
  description?: string;
  statusPageUrl?: string;
  region?: string;
  enabled: boolean;
  lastCheckedAt?: string;
  lastChangedAt?: string;
  createdAt: string;
};

export type Component = {
  id: string;
  serviceId: string;
  name: string;
  status: string;
  region?: string;
  description?: string;
  updatedAt: string;
};

export type Incident = {
  id: string;
  serviceId: string;
  externalId?: string;
  title: string;
  status: string;
  impact?: string;
  shortlink?: string;
  region?: string;
  createdAt: string;
  updatedAt: string;
  resolvedAt?: string;
};

export type IncidentUpdate = {
  id: string;
  incidentId: string;
  status: string;
  body: string;
  createdAt: string;
};

export type AlertTarget = {
  id: string;
  type: "slack" | "webhook" | "teams";
  name: string;
  url: string;
  secret?: string;
  enabled: boolean;
  filterRegion?: string;
  filterCategory?: string;
  createdAt: string;
};

export type Plugin = {
  id: string;
  name: string;
  type: string;
  config: {
    [key: string]: unknown;
  };
  enabled: boolean;
  createdAt: string;
};

export type VendorConfig = {
  id: string;
  name: string;
  category: string;
  statusPageUrl: string;
  ingestion: {
    type: "statuspage-api" | "rss" | "atom" | "scrape";
    url: string;
  };
  pollIntervalSeconds: number;
  defaultEnabled: boolean;
};

export type StatusOverview = {
  status: string;
  totalServices: number;
  activeIncidents: number;
  staleServices: number;
  byCategory: {
    [key: string]: {
      status: string;
      count: number;
    };
  };
  byRegion: {
    [key: string]: {
      status: string;
      count: number;
    };
  };
  lastUpdated: string;
};

export type AddServiceRequest = {
  vendorId: string;
  region?: string;
  enabled?: boolean;
};

export type UpdateServiceRequest = {
  name?: string;
  category?: string;
  region?: string;
  enabled?: boolean;
};

export type CreateAlertTargetRequest = {
  type: "slack" | "webhook" | "teams";
  name: string;
  url: string;
  secret?: string;
  enabled?: boolean;
  filterRegion?: string;
  filterCategory?: string;
};

export type CreatePluginRequest = {
  id?: string;
  name: string;
  type?: string;
  category?: string;
  config: {
    url: string;
    headers?: {
      [key: string]: string;
    };
    statusPath?: string;
    statusMapping?: {
      [key: string]: string;
    };
    region?: string;
  };
  enabled?: boolean;
};

export type UpdatePluginRequest = {
  name?: string;
  config?: {
    [key: string]: unknown;
  };
  enabled?: boolean;
};

export type StatusChange = {
  previousStatus: string;
  newStatus: string;
  changedAt: string;
};

export type UptimeStats = {
  percentage: number;
  totalChanges: number;
  lastOutage: string;
};

export type DailyUptime = {
  date: string;
  uptimePercent: number;
  status: string;
};

export type HistoryResponse = {
  changes: Array<StatusChange>;
  uptime: UptimeStats;
  dailyUptime: Array<DailyUptime>;
};

export type OkResponse = {
  ok: boolean;
};

export type ErrorResponse = {
  error: string;
};

export type GetStatusData = {
  body?: never;
  path?: never;
  query?: {
    region?: string;
  };
  url: "/status";
};

export type GetStatusResponses = {
  /**
   * Status overview
   */
  200: StatusOverview;
};

export type GetStatusResponse = GetStatusResponses[keyof GetStatusResponses];

export type GetServicesData = {
  body?: never;
  path?: never;
  query?: {
    region?: string;
    category?: string;
    enabled?: string;
  };
  url: "/services";
};

export type GetServicesResponses = {
  /**
   * Service list
   */
  200: {
    services: Array<Service>;
  };
};

export type GetServicesResponse = GetServicesResponses[keyof GetServicesResponses];

export type AddServiceData = {
  body: AddServiceRequest;
  path?: never;
  query?: never;
  url: "/services";
};

export type AddServiceResponses = {
  /**
   * Service added
   */
  201: {
    ok: boolean;
    id: string;
  };
};

export type AddServiceResponse = AddServiceResponses[keyof AddServiceResponses];

export type GetCatalogData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/services/catalog/all";
};

export type GetCatalogResponses = {
  /**
   * Vendor catalog
   */
  200: {
    vendors: Array<VendorConfig>;
  };
};

export type GetCatalogResponse = GetCatalogResponses[keyof GetCatalogResponses];

export type DeleteServiceData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/services/{id}";
};

export type DeleteServiceResponses = {
  /**
   * Deleted
   */
  200: OkResponse;
};

export type DeleteServiceResponse = DeleteServiceResponses[keyof DeleteServiceResponses];

export type GetServiceByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/services/{id}";
};

export type GetServiceByIdErrors = {
  /**
   * Not found
   */
  404: ErrorResponse;
};

export type GetServiceByIdError = GetServiceByIdErrors[keyof GetServiceByIdErrors];

export type GetServiceByIdResponses = {
  /**
   * Service with components
   */
  200: {
    service: Service;
    components: Array<Component>;
  };
};

export type GetServiceByIdResponse = GetServiceByIdResponses[keyof GetServiceByIdResponses];

export type UpdateServiceData = {
  body: UpdateServiceRequest;
  path: {
    id: string;
  };
  query?: never;
  url: "/services/{id}";
};

export type UpdateServiceResponses = {
  /**
   * Updated
   */
  200: OkResponse;
};

export type UpdateServiceResponse = UpdateServiceResponses[keyof UpdateServiceResponses];

export type GetIncidentsData = {
  body?: never;
  path?: never;
  query?: {
    active?: string;
    vendor?: string;
    region?: string;
    limit?: number;
  };
  url: "/incidents";
};

export type GetIncidentsResponses = {
  /**
   * Incident list
   */
  200: {
    incidents: Array<Incident>;
  };
};

export type GetIncidentsResponse = GetIncidentsResponses[keyof GetIncidentsResponses];

export type GetIncidentByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/incidents/{id}";
};

export type GetIncidentByIdErrors = {
  /**
   * Not found
   */
  404: ErrorResponse;
};

export type GetIncidentByIdError = GetIncidentByIdErrors[keyof GetIncidentByIdErrors];

export type GetIncidentByIdResponses = {
  /**
   * Incident with updates
   */
  200: {
    incident: Incident;
    updates: Array<IncidentUpdate>;
  };
};

export type GetIncidentByIdResponse = GetIncidentByIdResponses[keyof GetIncidentByIdResponses];

export type GetPublicStatusData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/public/status";
};

export type GetPublicStatusResponses = {
  /**
   * Status overview
   */
  200: StatusOverview;
};

export type GetPublicStatusResponse = GetPublicStatusResponses[keyof GetPublicStatusResponses];

export type GetPublicServicesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/public/services";
};

export type GetPublicServicesResponses = {
  /**
   * Service list
   */
  200: {
    services: Array<Service>;
  };
};

export type GetPublicServicesResponse =
  GetPublicServicesResponses[keyof GetPublicServicesResponses];

export type GetPublicIncidentsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/public/incidents";
};

export type GetPublicIncidentsResponses = {
  /**
   * Active incident list
   */
  200: {
    incidents: Array<Incident>;
  };
};

export type GetPublicIncidentsResponse =
  GetPublicIncidentsResponses[keyof GetPublicIncidentsResponses];

export type GetAlertTargetsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/alert-targets";
};

export type GetAlertTargetsResponses = {
  /**
   * Alert target list
   */
  200: {
    targets: Array<AlertTarget>;
  };
};

export type GetAlertTargetsResponse = GetAlertTargetsResponses[keyof GetAlertTargetsResponses];

export type CreateAlertTargetData = {
  body: CreateAlertTargetRequest;
  path?: never;
  query?: never;
  url: "/alert-targets";
};

export type CreateAlertTargetResponses = {
  /**
   * Created
   */
  201: {
    ok: boolean;
    id: string;
  };
};

export type CreateAlertTargetResponse =
  CreateAlertTargetResponses[keyof CreateAlertTargetResponses];

export type DeleteAlertTargetData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/alert-targets/{id}";
};

export type DeleteAlertTargetResponses = {
  /**
   * Deleted
   */
  200: OkResponse;
};

export type DeleteAlertTargetResponse =
  DeleteAlertTargetResponses[keyof DeleteAlertTargetResponses];

export type TestAlertTargetData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/alert-targets/{id}/test";
};

export type TestAlertTargetResponses = {
  /**
   * Test result
   */
  200: OkResponse;
};

export type TestAlertTargetResponse = TestAlertTargetResponses[keyof TestAlertTargetResponses];

export type GetPluginsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/plugins";
};

export type GetPluginsResponses = {
  /**
   * Plugin list
   */
  200: {
    plugins: Array<Plugin>;
  };
};

export type GetPluginsResponse = GetPluginsResponses[keyof GetPluginsResponses];

export type CreatePluginData = {
  body: CreatePluginRequest;
  path?: never;
  query?: never;
  url: "/plugins";
};

export type CreatePluginResponses = {
  /**
   * Created
   */
  201: {
    ok: boolean;
    id: string;
  };
};

export type CreatePluginResponse = CreatePluginResponses[keyof CreatePluginResponses];

export type GetHistoryData = {
  body?: never;
  path: {
    serviceId: string;
  };
  query?: {
    days?: number;
  };
  url: "/history/{serviceId}";
};

export type GetHistoryErrors = {
  /**
   * Service not found
   */
  404: ErrorResponse;
};

export type GetHistoryError = GetHistoryErrors[keyof GetHistoryErrors];

export type GetHistoryResponses = {
  /**
   * Uptime history
   */
  200: HistoryResponse;
};

export type GetHistoryResponse = GetHistoryResponses[keyof GetHistoryResponses];

export type DeletePluginData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/plugins/{id}";
};

export type DeletePluginResponses = {
  /**
   * Deleted
   */
  200: OkResponse;
};

export type DeletePluginResponse = DeletePluginResponses[keyof DeletePluginResponses];

export type UpdatePluginData = {
  body: UpdatePluginRequest;
  path: {
    id: string;
  };
  query?: never;
  url: "/plugins/{id}";
};

export type UpdatePluginResponses = {
  /**
   * Updated
   */
  200: OkResponse;
};

export type UpdatePluginResponse = UpdatePluginResponses[keyof UpdatePluginResponses];
