// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  addService,
  createAlertTarget,
  createPlugin,
  deleteAlertTarget,
  deletePlugin,
  deleteService,
  getAlertTargets,
  getCatalog,
  getHistory,
  getIncidentById,
  getIncidents,
  getPlugins,
  getPublicIncidents,
  getPublicServices,
  getPublicStatus,
  getServiceById,
  getServices,
  getStatus,
  type Options,
  testAlertTarget,
  updatePlugin,
  updateService,
} from "../sdk.gen";
import type {
  AddServiceData,
  AddServiceResponse,
  CreateAlertTargetData,
  CreateAlertTargetResponse,
  CreatePluginData,
  CreatePluginResponse,
  DeleteAlertTargetData,
  DeleteAlertTargetResponse,
  DeletePluginData,
  DeletePluginResponse,
  DeleteServiceData,
  DeleteServiceResponse,
  GetAlertTargetsData,
  GetAlertTargetsResponse,
  GetCatalogData,
  GetCatalogResponse,
  GetHistoryData,
  GetHistoryError,
  GetHistoryResponse,
  GetIncidentByIdData,
  GetIncidentByIdError,
  GetIncidentByIdResponse,
  GetIncidentsData,
  GetIncidentsResponse,
  GetPluginsData,
  GetPluginsResponse,
  GetPublicIncidentsData,
  GetPublicIncidentsResponse,
  GetPublicServicesData,
  GetPublicServicesResponse,
  GetPublicStatusData,
  GetPublicStatusResponse,
  GetServiceByIdData,
  GetServiceByIdError,
  GetServiceByIdResponse,
  GetServicesData,
  GetServicesResponse,
  GetStatusData,
  GetStatusResponse,
  TestAlertTargetData,
  TestAlertTargetResponse,
  UpdatePluginData,
  UpdatePluginResponse,
  UpdateServiceData,
  UpdateServiceResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getStatusQueryKey = (options?: Options<GetStatusData>) =>
  createQueryKey("getStatus", options);

/**
 * Aggregate status overview
 */
export const getStatusOptions = (options?: Options<GetStatusData>) =>
  queryOptions<
    GetStatusResponse,
    DefaultError,
    GetStatusResponse,
    ReturnType<typeof getStatusQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getStatus({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getStatusQueryKey(options),
  });

export const getServicesQueryKey = (options?: Options<GetServicesData>) =>
  createQueryKey("getServices", options);

/**
 * List monitored services
 */
export const getServicesOptions = (options?: Options<GetServicesData>) =>
  queryOptions<
    GetServicesResponse,
    DefaultError,
    GetServicesResponse,
    ReturnType<typeof getServicesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getServices({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getServicesQueryKey(options),
  });

/**
 * Add/enable a vendor for monitoring
 */
export const addServiceMutation = (
  options?: Partial<Options<AddServiceData>>
): UseMutationOptions<AddServiceResponse, DefaultError, Options<AddServiceData>> => {
  const mutationOptions: UseMutationOptions<
    AddServiceResponse,
    DefaultError,
    Options<AddServiceData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await addService({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getCatalogQueryKey = (options?: Options<GetCatalogData>) =>
  createQueryKey("getCatalog", options);

/**
 * List all available vendors from catalog
 */
export const getCatalogOptions = (options?: Options<GetCatalogData>) =>
  queryOptions<
    GetCatalogResponse,
    DefaultError,
    GetCatalogResponse,
    ReturnType<typeof getCatalogQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCatalog({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getCatalogQueryKey(options),
  });

/**
 * Delete a service
 */
export const deleteServiceMutation = (
  options?: Partial<Options<DeleteServiceData>>
): UseMutationOptions<DeleteServiceResponse, DefaultError, Options<DeleteServiceData>> => {
  const mutationOptions: UseMutationOptions<
    DeleteServiceResponse,
    DefaultError,
    Options<DeleteServiceData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteService({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getServiceByIdQueryKey = (options: Options<GetServiceByIdData>) =>
  createQueryKey("getServiceById", options);

/**
 * Get service details with components
 */
export const getServiceByIdOptions = (options: Options<GetServiceByIdData>) =>
  queryOptions<
    GetServiceByIdResponse,
    GetServiceByIdError,
    GetServiceByIdResponse,
    ReturnType<typeof getServiceByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getServiceById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getServiceByIdQueryKey(options),
  });

/**
 * Update a service
 */
export const updateServiceMutation = (
  options?: Partial<Options<UpdateServiceData>>
): UseMutationOptions<UpdateServiceResponse, DefaultError, Options<UpdateServiceData>> => {
  const mutationOptions: UseMutationOptions<
    UpdateServiceResponse,
    DefaultError,
    Options<UpdateServiceData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateService({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getIncidentsQueryKey = (options?: Options<GetIncidentsData>) =>
  createQueryKey("getIncidents", options);

/**
 * List incidents
 */
export const getIncidentsOptions = (options?: Options<GetIncidentsData>) =>
  queryOptions<
    GetIncidentsResponse,
    DefaultError,
    GetIncidentsResponse,
    ReturnType<typeof getIncidentsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getIncidents({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getIncidentsQueryKey(options),
  });

export const getIncidentByIdQueryKey = (options: Options<GetIncidentByIdData>) =>
  createQueryKey("getIncidentById", options);

/**
 * Get incident with updates
 */
export const getIncidentByIdOptions = (options: Options<GetIncidentByIdData>) =>
  queryOptions<
    GetIncidentByIdResponse,
    GetIncidentByIdError,
    GetIncidentByIdResponse,
    ReturnType<typeof getIncidentByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getIncidentById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getIncidentByIdQueryKey(options),
  });

export const getPublicStatusQueryKey = (options?: Options<GetPublicStatusData>) =>
  createQueryKey("getPublicStatus", options);

/**
 * Public aggregate status overview (no auth)
 */
export const getPublicStatusOptions = (options?: Options<GetPublicStatusData>) =>
  queryOptions<
    GetPublicStatusResponse,
    DefaultError,
    GetPublicStatusResponse,
    ReturnType<typeof getPublicStatusQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPublicStatus({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getPublicStatusQueryKey(options),
  });

export const getPublicServicesQueryKey = (options?: Options<GetPublicServicesData>) =>
  createQueryKey("getPublicServices", options);

/**
 * Public list of enabled services (no auth)
 */
export const getPublicServicesOptions = (options?: Options<GetPublicServicesData>) =>
  queryOptions<
    GetPublicServicesResponse,
    DefaultError,
    GetPublicServicesResponse,
    ReturnType<typeof getPublicServicesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPublicServices({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getPublicServicesQueryKey(options),
  });

export const getPublicIncidentsQueryKey = (options?: Options<GetPublicIncidentsData>) =>
  createQueryKey("getPublicIncidents", options);

/**
 * Public list of active incidents (no auth)
 */
export const getPublicIncidentsOptions = (options?: Options<GetPublicIncidentsData>) =>
  queryOptions<
    GetPublicIncidentsResponse,
    DefaultError,
    GetPublicIncidentsResponse,
    ReturnType<typeof getPublicIncidentsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPublicIncidents({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getPublicIncidentsQueryKey(options),
  });

export const getAlertTargetsQueryKey = (options?: Options<GetAlertTargetsData>) =>
  createQueryKey("getAlertTargets", options);

/**
 * List alert targets
 */
export const getAlertTargetsOptions = (options?: Options<GetAlertTargetsData>) =>
  queryOptions<
    GetAlertTargetsResponse,
    DefaultError,
    GetAlertTargetsResponse,
    ReturnType<typeof getAlertTargetsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAlertTargets({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAlertTargetsQueryKey(options),
  });

/**
 * Create an alert target
 */
export const createAlertTargetMutation = (
  options?: Partial<Options<CreateAlertTargetData>>
): UseMutationOptions<CreateAlertTargetResponse, DefaultError, Options<CreateAlertTargetData>> => {
  const mutationOptions: UseMutationOptions<
    CreateAlertTargetResponse,
    DefaultError,
    Options<CreateAlertTargetData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createAlertTarget({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete an alert target
 */
export const deleteAlertTargetMutation = (
  options?: Partial<Options<DeleteAlertTargetData>>
): UseMutationOptions<DeleteAlertTargetResponse, DefaultError, Options<DeleteAlertTargetData>> => {
  const mutationOptions: UseMutationOptions<
    DeleteAlertTargetResponse,
    DefaultError,
    Options<DeleteAlertTargetData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteAlertTarget({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Send a test alert
 */
export const testAlertTargetMutation = (
  options?: Partial<Options<TestAlertTargetData>>
): UseMutationOptions<TestAlertTargetResponse, DefaultError, Options<TestAlertTargetData>> => {
  const mutationOptions: UseMutationOptions<
    TestAlertTargetResponse,
    DefaultError,
    Options<TestAlertTargetData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await testAlertTarget({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getPluginsQueryKey = (options?: Options<GetPluginsData>) =>
  createQueryKey("getPlugins", options);

/**
 * List plugins
 */
export const getPluginsOptions = (options?: Options<GetPluginsData>) =>
  queryOptions<
    GetPluginsResponse,
    DefaultError,
    GetPluginsResponse,
    ReturnType<typeof getPluginsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPlugins({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getPluginsQueryKey(options),
  });

/**
 * Register a custom status plugin
 */
export const createPluginMutation = (
  options?: Partial<Options<CreatePluginData>>
): UseMutationOptions<CreatePluginResponse, DefaultError, Options<CreatePluginData>> => {
  const mutationOptions: UseMutationOptions<
    CreatePluginResponse,
    DefaultError,
    Options<CreatePluginData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createPlugin({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getHistoryQueryKey = (options: Options<GetHistoryData>) =>
  createQueryKey("getHistory", options);

/**
 * Get uptime history and status changes for a service
 */
export const getHistoryOptions = (options: Options<GetHistoryData>) =>
  queryOptions<
    GetHistoryResponse,
    GetHistoryError,
    GetHistoryResponse,
    ReturnType<typeof getHistoryQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getHistory({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getHistoryQueryKey(options),
  });

/**
 * Delete a plugin and its service
 */
export const deletePluginMutation = (
  options?: Partial<Options<DeletePluginData>>
): UseMutationOptions<DeletePluginResponse, DefaultError, Options<DeletePluginData>> => {
  const mutationOptions: UseMutationOptions<
    DeletePluginResponse,
    DefaultError,
    Options<DeletePluginData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deletePlugin({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update a plugin
 */
export const updatePluginMutation = (
  options?: Partial<Options<UpdatePluginData>>
): UseMutationOptions<UpdatePluginResponse, DefaultError, Options<UpdatePluginData>> => {
  const mutationOptions: UseMutationOptions<
    UpdatePluginResponse,
    DefaultError,
    Options<UpdatePluginData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updatePlugin({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
